apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-bridge-gke-dev-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps' # Update to match your fork.
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: gitops-bridge-gke-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true